#!/bin/bash

set -euo pipefail

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

if [ -f "/usr/lib/openssh/sftp-server" ];then
    srv="/usr/lib/openssh/sftp-server"
elif [ -f "/usr/lib/ssh/sftp-server" ];then
    srv="/usr/lib/ssh/sftp-server"
else
    echo "can't find openssh sftp-server" >&2
    exit 1
fi

export LD_PRELOAD="$SCRIPTPATH/libsftp_server_chroot_preload.so"
if [ ! -f "$LD_PRELOAD" ];then
    echo "can't find $LD_PRELOAD" >&2
    exit 1
fi

exec "$srv" "$@"
